pfDB = {
  ["areatrigger"] = {},
  ["items"] = {},
  ["meta"] = {},
  ["minimap"] = {},
  ["objects"] = {},
  ["professions"] = {},
  ["quests"] = {},
  ["quests-itemreq"] = {},
  ["questxp"] = {},
  ["refloot"] = {},
  ["units"] = {},
  ["zones"] = {},
  ["worldmaparea"] = {},
}
